// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlotwgbmsnsqsjnrhvqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsb3R3Z2Jtc25zcXNqbnJodnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTk1NDcsImV4cCI6MjA2NDI3NTU0N30.Fe9uLgqtQSafQQRDyKe3co8lHbCyz0RNmYz2k8zWvqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);