// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pknhbvumbrcmhmdmgnft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrbmhidnVtYnJjbWhtZG1nbmZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTk2MTUsImV4cCI6MjA2NDI3NTYxNX0.NL7aL2So5B7_qFYT2w_5LtvMS2_bhhWom04q8f6xhaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);